USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = N'бобор')
BEGIN
    ALTER DATABASE бобор SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE бобор;
END
GO

CREATE DATABASE бобор COLLATE Cyrillic_General_CI_AS;
GO